version: '3.8'

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file

networks:
  default:
    name: devnet

services:
  lotus:
    container_name: lotus
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-lotus.sh']
    healthcheck:
      test: >-
        curl -s -X POST -H "Content-Type: application/json"
        --data '{ "jsonrpc": "2.0", "method": "Filecoin.ChainHead", "params": [], "id": 1 }'
        http://lotus:1234/rpc/v0 || exit 1
      interval: 20s
      retries: 5
      start_period: 6000s
      timeout: 10s
    ports:
      - "1234:1234"
      - "9090:9090"
    environment:
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
      - LOTUS_FEVM_ENABLEETHRPC=true
      - LOTUS_API_LISTENADDRESS=/dns/lotus/tcp/1234/http
      - LOTUS_LIBP2P_LISTENADDRESSES=/ip4/0.0.0.0/tcp/9090
      - LOTUS_SKIP_GENESIS_CHECK=_yes_
      - GENESIS_PATH=/var/lib/genesis
      - SECTOR_SIZE=${SECTOR_SIZE}
      - MNEMONIC=${MNEMONIC}
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/lotus:/var/lib/lotus:rw
      - ./data/genesis:/var/lib/genesis:rw


  lotus-miner:
    container_name: lotus-miner
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-lotus-miner.sh']
    healthcheck:
      test: >-
        curl -s http://lotus-miner:2345 || exit 1
      interval: 20s
      retries: 5
      start_period: 6000s
      timeout: 10s
    depends_on:
      lotus:
        condition: service_healthy
    ports:
      - "2345:2345"
    environment:
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
      - LOTUS_API_LISTENADDRESS=/dns/lotus-miner/tcp/2345/http
      - LOTUS_API_REMOTELISTENADDRESS=lotus-miner:2345
      - LOTUS_SEALING_BATCHPRECOMMITS=false
      - LOTUS_SEALING_AGGREGATECOMMITS=false
      - LOTUS_SUBSYSTEMS_ENABLEMARKETS=false
      - LOTUS_SEALING_WAITDEALSDELAY=20s
      - LOTUS_SKIP_GENESIS_CHECK=_yes_
      - GENESIS_PATH=/var/lib/genesis
      - SECTOR_SIZE=${SECTOR_SIZE}
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/lotus-miner:/var/lib/lotus-miner:rw
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/genesis:/var/lib/genesis:ro
#      - ${FIL_PROOFS_PARAMETER_CACHE}:/var/tmp/filecoin-proof-parameters:rw

  lotus-miner2:
    container_name: lotus-miner2
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-lotus-miner2.sh']
    profiles: ["replication"]
    healthcheck:
      test: >-
        curl -s http://lotus-miner2:2345 || exit 1
      interval: 20s
      retries: 5
      start_period: 6000s
      timeout: 10s
    depends_on:
      lotus-miner:
        condition: service_healthy
    ports:
      - "2346:2345"
    environment:
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
      - LOTUS_API_LISTENADDRESS=/dns/lotus-miner2/tcp/2345/http
      - LOTUS_API_REMOTELISTENADDRESS=lotus-miner2:2345
      - LOTUS_SEALING_BATCHPRECOMMITS=false
      - LOTUS_SEALING_AGGREGATECOMMITS=false
      - LOTUS_SUBSYSTEMS_ENABLEMARKETS=false
      - LOTUS_SEALING_WAITDEALSDELAY=20s
      - GENESIS_PATH=/var/lib/genesis
      - SECTOR_SIZE=${SECTOR_SIZE}
#      - LOTUS_SKIP_GENESIS_CHECK=_yes_
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/lotus-miner2:/var/lib/lotus-miner:rw
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/genesis:/var/lib/genesis:ro

  boost:
    container_name: boost
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-boost.sh']    
    healthcheck:
      test: >-
        curl -s http://boost:8080 || exit 1
      interval: 20s
      retries: 5
      start_period: 6000s
      timeout: 10s
    depends_on:
        lotus:
          condition: service_healthy
        lotus-miner:
          condition: service_healthy
    ports:
      - "8080:8080"
      - "1288:1288" # For the /metrics endpoint
      - "50000:50000" # Exposed libp2p port
    environment:
      - LOTUS_API_LISTENADDRESS=/dns/boost/tcp/1288/http
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
      - LOTUS_TRACING_ENABLED=true
      - LOTUS_TRACING_SERVICENAME=boostd
      - LOTUS_TRACING_ENDPOINT=http://tempo:14268/api/traces
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/boost:/var/lib/boost:rw
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner:/var/lib/lotus-miner:ro
      - ./data/sample:/app/public:rw

  booster-http:
    container_name: booster-http
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-booster-http.sh']
    healthcheck:
      test: >-
        curl http://127.0.0.1:7777/ || echo down
      interval: 20s
      retries: 5
      start_period: 6000s
      timeout: 10s
    depends_on:
        boost:
          condition: service_healthy
    ports:
      - "7777:7777"
    environment:
      - BOOST_PATH=/var/lib/boost
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/boost:/var/lib/boost:ro
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner:/var/lib/lotus-miner:ro
    labels:
      - "com.docker-tc.enabled=1"
      - "com.docker-tc.delay=10ms"

  booster-bitswap:
    container_name: booster-bitswap
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-booster-bitswap.sh']
    healthcheck:
      test: >-
        printf "" > /dev/tcp/127.0.0.1/8888 || echo down
      interval: 20s
      retries: 5
      start_period: 6000s
      timeout: 10s

    depends_on:
        boost:
          condition: service_healthy
    ports:
      - "8888:8888"
    environment:
      - BOOSTER_BITSWAP_REPO=/var/lib/booster-bitswap
      - BOOST_PATH=/var/lib/boost
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/booster-bitswap:/var/lib/booster-bitswap:rw
      - ./data/boost:/var/lib/boost:ro
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner:/var/lib/lotus-miner:ro
    labels:
      - "com.docker-tc.enabled=1"
      - "com.docker-tc.delay=10ms"

  boost2:
    container_name: boost2
    image: ${IMAGE}
    profiles: ["replication"]
    entrypoint: ['/app/entrypoint-boost.sh']    
    healthcheck:
      test: >-
        curl -s http://boost2:8080 || exit 1
      interval: 20s
      retries: 5
      start_period: 6000s
      timeout: 10s
    depends_on:
        lotus:
          condition: service_healthy
        lotus-miner2:
          condition: service_healthy
    ports:
      - "8081:8080"
      - "1289:1288" # For the /metrics endpoint
      - "50001:50000" # Exposed libp2p port
    environment:
      - LOTUS_API_LISTENADDRESS=/dns/boost2/tcp/1288/http
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
      - LOTUS_TRACING_ENABLED=true
      - LOTUS_TRACING_SERVICENAME=boostd
      - LOTUS_TRACING_ENDPOINT=http://tempo:14268/api/traces
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/boost2:/var/lib/boost:rw
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner2:/var/lib/lotus-miner:ro
      - ./data/sample:/app/public:rw

  booster-http2:
    container_name: booster-http2
    image: ${IMAGE}
    profiles: ["replication"]
    entrypoint: ['/app/entrypoint-booster-http.sh']
    healthcheck:
      test: >-
        curl http://127.0.0.1:7778/ || echo down
      interval: 20s
      retries: 5
      start_period: 6000s
      timeout: 10s
    depends_on:
      boost2:
        condition: service_healthy
    ports:
      - "7778:7777"
    environment:
      - BOOST_PATH=/var/lib/boost
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/boost2:/var/lib/boost:ro
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner2:/var/lib/lotus-miner:ro
    labels:
      - "com.docker-tc.enabled=1"
      - "com.docker-tc.delay=10ms"

  booster-bitswap2:
    container_name: booster-bitswap2
    image: ${IMAGE}
    profiles: ["replication"]    
    entrypoint: ['/app/entrypoint-booster-bitswap.sh']
    healthcheck:
      test: >-
        printf "" > /dev/tcp/127.0.0.1/8889 || echo down
      interval: 20s
      retries: 5
      start_period: 6000s
      timeout: 10s
    depends_on:
      boost2:
        condition: service_healthy
    ports:
      - "8889:8888"
    environment:
      - BOOSTER_BITSWAP_REPO=/var/lib/booster-bitswap
      - BOOST_PATH=/var/lib/boost
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/booster-bitswap2:/var/lib/booster-bitswap:rw
      - ./data/boost2:/var/lib/boost:ro
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner2:/var/lib/lotus-miner:ro
    labels:
      - "com.docker-tc.enabled=1"
      - "com.docker-tc.delay=10ms"
