FROM ghcr.io/filecoin-project/filecoin-fvm-localnet:main AS filecoin-fvm-localnet-preproofs-2k
RUN lotus fetch-params 2048

FROM ghcr.io/filecoin-project/filecoin-fvm-localnet:main AS filecoin-fvm-localnet-preproofs-8m
RUN lotus fetch-params 8388608
